# -*- coding: utf-8 -*-
"""prediksi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrdA7IG1ZO-oUXtLgJWa2cn8NPi7_RN6

OverTime: Masukan 1 untuk ya 0 untuk tidak

MaritalStatus_Single: Masukan 1 untuk ya 0 untuk tidak

JobRole_Sales Representative: Masukan 1 untuk ya 0 untuk tidak

JobRole_Laboratory Technician: Masukan 1 untuk ya 0 untuk tidak

BusinessTravel_Travel_Frequently: Masukan 1 untuk ya 0 untuk tidak

EnvironmentSatisfaction: 1-Low, 2-Medium, 3-High, 4-Very High

YearsAtCompany: berapa tahun

JobInvolvement: 1-Low, 2-Medium, 3-High, 4-Very High

YearsWithCurrManager: berapa tahun

YearsInCurrentRole: berapa tahun

MonthlyIncome: masukkan gaji

StockOptionLevel: Stock Option Level

JobLevel: Level of job (1 to 5)

Age: Age

TotalWorkingYears: berapa tahun
"""

import joblib
import pandas as pd

# Load model
model = joblib.load("model.pkl")

# Load data input
new_data = {
    'OverTime': [1],
    'MaritalStatus_Single': [0],
    'JobRole_Sales Representative': [0],
    'JobRole_Laboratory Technician': [1],
    'BusinessTravel_Travel_Frequently': [1],
    'EnvironmentSatisfaction': [2],
    'YearsAtCompany': [2],
    'JobInvolvement': [2],
    'YearsWithCurrManager': [1],
    'YearsInCurrentRole': [1],
    'MonthlyIncome': [2500],
    'StockOptionLevel': [1],
    'JobLevel': [2],
    'Age': [19],
    'TotalWorkingYears': [2]
}

# Convert data input menjadi DataFrame
input_df = pd.DataFrame(new_data)

# Lakukan prediksi
prediksi = model.predict(input_df)

# Tampilkan hasil
print("Hasil Prediksi:")
print(prediksi)