# -*- coding: utf-8 -*-
"""prediksi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrdA7IG1ZO-oUXtLgJWa2cn8NPi7_RN6
"""

import joblib
import pandas as pd

# Petunjuk dan input dari user
print("Silakan isi data berikut untuk prediksi Attrition:\n")

input_data = {
    'OverTime': [int(input("OverTime (1 = ya, 0 = tidak): "))],
    'MaritalStatus_Single': [int(input("MaritalStatus_Single (1 = ya, 0 = tidak): "))],
    'JobRole_Sales Representative': [int(input("JobRole_Sales Representative (1 = ya, 0 = tidak): "))],
    'JobRole_Laboratory Technician': [int(input("JobRole_Laboratory Technician (1 = ya, 0 = tidak): "))],
    'BusinessTravel_Travel_Frequently': [int(input("BusinessTravel_Travel_Frequently (1 = ya, 0 = tidak): "))],
    'EnvironmentSatisfaction': [int(input("EnvironmentSatisfaction (1 = Low, 2 = Medium, 3 = High, 4 = Very High): "))],
    'YearsAtCompany': [int(input("YearsAtCompany (berapa tahun): "))],
    'JobInvolvement': [int(input("JobInvolvement (1 = Low, 2 = Medium, 3 = High, 4 = Very High): "))],
    'YearsWithCurrManager': [int(input("YearsWithCurrManager (berapa tahun): "))],
    'YearsInCurrentRole': [int(input("YearsInCurrentRole (berapa tahun): "))],
    'MonthlyIncome': [float(input("MonthlyIncome (masukkan gaji): "))],
    'StockOptionLevel': [int(input("StockOptionLevel (0-3): "))],
    'JobLevel': [int(input("JobLevel (1 sampai 5): "))],
    'Age': [int(input("Age (usia): "))],
    'TotalWorkingYears': [int(input("TotalWorkingYears (berapa tahun): "))]
}

# Convert ke DataFrame
input_df = pd.DataFrame(input_data)

# Load model
model = joblib.load("model.pkl")

# Lakukan prediksi
prediksi = model.predict(input_df)

# Tampilkan hasil
print("Hasil Prediksi:")
print(prediksi)